### ISSUE TITLE
DataFrame input support for ens.batch()

### ISSUE THREAD

**Issue by mi-dai** [lincc-frameworks/tape#258]
Currently using a Custom Analysis Function through ens.batch() only support array as input to the function. Suggest supporting pandas DataFrame as input.

**Comment by dougbrn** [comment]
Likely not a complete solution to this (@mi-dai let me know if it is), but the batch function tutorial now has [an example](https://tape.readthedocs.io/en/latest/tutorials/batch_showcase.html#Case-4:-Functions-that-Require-Non-Array-Inputs)  for handling non-array inputs with the current API.

**Comment by nevencaplar** [comment]
@mi-dai When you get a chance, can you check if the comment by @dougbrn fulfills your needs?

**Comment by mi-dai** [comment]
This looks good to me. Although there are caveats like when the function uses dataframes from both source and object tables, users have to work around to get it to really work (see issue [#271](https://github.com/lincc-frameworks/tape/issues/271))
Also I'm not so sure about this line `res1 = ens.batch(mean_wrapper, "flux")`
I think when I tried this I need to use `my_flux`(which is the column name defined in the Dataframe) instead of `flux`

**Comment by dougbrn** [comment]
Thanks for taking a look! The example is pretty basic, and "flux" ends up being the input because we are actually constructing the dataframe from the ensemble columns (which has "flux"), mapping it to "my_flux" which is the constructed dataframe column. But from the ensembles perspective it doesn't know anything about "my_flux" as that's defined for the actual function being applied through batch itself.

I'm hoping we can get to #271 sometime this quarter, as it's something that I believe I attempted to get working but not surprised that it doesn't given that it hasn't been tested much.

**Comment by nevencaplar** [comment]
Ok, I am closing this now as resolved. Possibly follow-up in separate tickets.
